/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Boundary.Tutor;

import Controller.TutorController;
import Entity.Tutor;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;

/**
 *
 * @author CY
 */
public class ModifyDetailsDialog extends javax.swing.JDialog {

    /**
     * Creates new form ModifyDetailsDialog
     */
    public ModifyDetailsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public ModifyDetailsDialog(java.awt.Frame parent, boolean modal, Tutor tutor) {
        super(parent, modal);
        initComponents();
        oldTutor = tutor;
        initializeData();
    }

    private void initializeData() {
        tutorIdField.setText(oldTutor.getTutorId());
        nameField.setText(oldTutor.getName());
        contactField.setText(oldTutor.getContact());
        genderField.setSelectedItem(oldTutor.getGender());
        qualificationField.setSelectedItem(oldTutor.getQualification());
        ageField.setValue(oldTutor.getAge());
    }
    
    private void initializeGenderField() {
        Field[] fields = Tutor.Genders.class.getDeclaredFields();
        for (Field field : fields) {
            if (Modifier.isStatic(field.getModifiers()) && Modifier.isFinal(field.getModifiers())) {
                try {
                    genderField.addItem((String) field.get(null));
                } catch (IllegalAccessException ex) {
                    resultMessage.setText("Failed to initialize gender options");
                }
            }
        }
    }

    private void initializeQualificationField() {
        Field[] fields = Tutor.Qualifications.class.getDeclaredFields();
        for (Field field : fields) {
            if (Modifier.isStatic(field.getModifiers()) && Modifier.isFinal(field.getModifiers())) {
                try {
                    qualificationField.addItem((String) field.get(null));
                } catch (IllegalAccessException ex) {
                    resultMessage.setText("Failed to initialize gender options");
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tutorIdField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        confirmModifyBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        genderField = new javax.swing.JComboBox<>();
        initializeGenderField();
        ageField = new javax.swing.JSpinner();
        qualificationField = new javax.swing.JComboBox<>();
        initializeQualificationField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        contactField = new javax.swing.JTextField();
        resultMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(372, 362));
        setMinimumSize(new java.awt.Dimension(372, 362));
        setResizable(false);

        tutorIdField.setEnabled(false);
        tutorIdField.setMaximumSize(new java.awt.Dimension(122, 22));
        tutorIdField.setMinimumSize(new java.awt.Dimension(122, 22));
        tutorIdField.setPreferredSize(new java.awt.Dimension(122, 22));
        tutorIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorIdFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Tutor Id");

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        confirmModifyBtn.setText("Confirm");
        confirmModifyBtn.setMaximumSize(new java.awt.Dimension(66, 22));
        confirmModifyBtn.setMinimumSize(new java.awt.Dimension(66, 22));
        confirmModifyBtn.setPreferredSize(new java.awt.Dimension(66, 22));
        confirmModifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmModifyBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Contact");

        jLabel4.setText("Gender");

        jLabel3.setText("Name");

        jLabel7.setText("Age");

        jLabel6.setText("Qualification");

        resultMessage.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultMessage)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(44, 44, 44)
                            .addComponent(tutorIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(113, 113, 113))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(qualificationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(53, 53, 53)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmModifyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tutorIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(qualificationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(resultMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(confirmModifyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tutorIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tutorIdFieldActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void confirmModifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmModifyBtnActionPerformed
        Tutor newTutor = new Tutor();
        TutorController tutorController = TutorController.getInstance();

        if (nameField.getText().equals("")) {
            resultMessage.setText("Name cannot be empty");
            return;
        }
        if (contactField.getText().equals("")) {
            resultMessage.setText("Contact cannot be empty");
            return;
        }
        if (((int) ageField.getValue()) < 18 || ((int) ageField.getValue()) > 120) {
            resultMessage.setText("Invalid Age");
            return;
        }

        newTutor.setTutorId(tutorIdField.getText());
        newTutor.setName(nameField.getText());
        newTutor.setContact(contactField.getText());
        newTutor.setGender((String) genderField.getSelectedItem());
        newTutor.setQualification((String) qualificationField.getSelectedItem());
        newTutor.setAge((int) ageField.getValue());
        
        try {
            if(tutorController.replaceTutor(oldTutor, newTutor) != null) {
                resultMessage.setText("Tutor " + oldTutor.getTutorId() + " modified successfully!");
            } else {
                resultMessage.setText("Modify failed");
            }
        } catch (IndexOutOfBoundsException ex) {
            resultMessage.setText("Index out of bound");
        } finally {
            clearInputField();
        }
    }//GEN-LAST:event_confirmModifyBtnActionPerformed

    private void clearInputField() {
        tutorIdField.setText("");
        nameField.setText("");
        contactField.setText("");
        genderField.setSelectedIndex(0);
        qualificationField.setSelectedIndex(0);
        ageField.setValue(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModifyDetailsDialog dialog = new ModifyDetailsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private Tutor oldTutor;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ageField;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton confirmModifyBtn;
    private javax.swing.JTextField contactField;
    private javax.swing.JComboBox<String> genderField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameField;
    private javax.swing.JComboBox<String> qualificationField;
    private javax.swing.JLabel resultMessage;
    private javax.swing.JTextField tutorIdField;
    // End of variables declaration//GEN-END:variables
}
