/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Boundary.Tutor;

import ADT.Impl.ArraySetUniqueList;
import Controller.TutorController;
import Entity.Tutor;
import Utility.TutorUtil;
import java.util.function.BiFunction;
import javax.swing.JDialog;

/**
 *
 * @author Hoo Chun Yuan
 */
public class ReportDialog extends javax.swing.JDialog {

    /**
     * Creates new form ReportDialog
     */
    public ReportDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        this.modal = modal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        topFiveHighestPayBtn = new javax.swing.JButton();
        topFiveHighestAgeBtn = new javax.swing.JButton();
        topFiveLowestPayBtn = new javax.swing.JButton();
        topFiveLowestAgeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Generate Tutor Report");

        topFiveHighestPayBtn.setText("Top 5 tutor highest paid");
        topFiveHighestPayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topFiveHighestPayBtnActionPerformed(evt);
            }
        });

        topFiveHighestAgeBtn.setText("Top 5 tutor highest age");
        topFiveHighestAgeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topFiveHighestAgeBtnActionPerformed(evt);
            }
        });

        topFiveLowestPayBtn.setText("Top 5 tutor lowest paid");
        topFiveLowestPayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topFiveLowestPayBtnActionPerformed(evt);
            }
        });

        topFiveLowestAgeBtn.setText("Top 5 tutor lowest age");
        topFiveLowestAgeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topFiveLowestAgeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(topFiveHighestPayBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(topFiveLowestAgeBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(topFiveHighestAgeBtn)
                                .addComponent(topFiveLowestPayBtn)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(topFiveHighestPayBtn)
                .addGap(18, 18, 18)
                .addComponent(topFiveLowestPayBtn)
                .addGap(18, 18, 18)
                .addComponent(topFiveHighestAgeBtn)
                .addGap(18, 18, 18)
                .addComponent(topFiveLowestAgeBtn)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void topFiveHighestPayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topFiveHighestPayBtnActionPerformed
        BiFunction<Tutor, Tutor, Boolean> fiveHighestPayFunction = (a, b) -> a.getSalary().compareTo(b.getSalary()) > 0;
        proceedGenerateReport(fiveHighestPayFunction);
    }//GEN-LAST:event_topFiveHighestPayBtnActionPerformed

    private void topFiveHighestAgeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topFiveHighestAgeBtnActionPerformed
        BiFunction<Tutor, Tutor, Boolean> fiveHighestAgeFunction = (a, b) -> a.getAge().compareTo(b.getAge()) > 0;
        proceedGenerateReport(fiveHighestAgeFunction);
    }//GEN-LAST:event_topFiveHighestAgeBtnActionPerformed

    private void topFiveLowestPayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topFiveLowestPayBtnActionPerformed
        BiFunction<Tutor, Tutor, Boolean> fiveLowestPayFunction = (a, b) -> a.getSalary().compareTo(b.getSalary()) < 0;
        proceedGenerateReport(fiveLowestPayFunction);
    }//GEN-LAST:event_topFiveLowestPayBtnActionPerformed

    private void topFiveLowestAgeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topFiveLowestAgeBtnActionPerformed
        BiFunction<Tutor, Tutor, Boolean> fiveLowestAgeFunction = (a, b) -> a.getAge().compareTo(b.getAge()) < 0;
        proceedGenerateReport(fiveLowestAgeFunction);
    }//GEN-LAST:event_topFiveLowestAgeBtnActionPerformed

    private void proceedGenerateReport(BiFunction<Tutor, Tutor, Boolean> tutorSortCriteriaFunction) {
        TutorController tutorController = TutorController.getInstance();
        ArraySetUniqueList<Tutor> sortedTutorList = TutorUtil.sortTutor(tutorController.getTutorList(), tutorSortCriteriaFunction);
        int i = sortedTutorList.size() < 5 ? sortedTutorList.size() - 1 : 4;
        ArraySetUniqueList<Tutor> result = (ArraySetUniqueList<Tutor>) sortedTutorList.subList(0, i);

        JDialog findResultDialog = new ResultDialog(parent, modal, result);
        findResultDialog.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReportDialog dialog = new ReportDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    java.awt.Frame parent;
    boolean modal;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton topFiveHighestAgeBtn;
    private javax.swing.JButton topFiveHighestPayBtn;
    private javax.swing.JButton topFiveLowestAgeBtn;
    private javax.swing.JButton topFiveLowestPayBtn;
    // End of variables declaration//GEN-END:variables
}
