/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Boundary.Tutor;

import Boundary.MainFrame;
import javax.swing.JDialog;


/**
 *
 * @author CY
 */
public class TutorManagementFrame extends javax.swing.JFrame {

    /**
     * Creates new form Tutor
     */
    public TutorManagementFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addTutorBtn = new javax.swing.JButton();
        removeTutorBtn = new javax.swing.JButton();
        findTutorBtn = new javax.swing.JButton();
        modifyTutorBtn = new javax.swing.JButton();
        viewTutorsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        reportBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        addTutorBtn.setText("Add Tutor");
        addTutorBtn.setMaximumSize(new java.awt.Dimension(104, 22));
        addTutorBtn.setMinimumSize(new java.awt.Dimension(104, 22));
        addTutorBtn.setPreferredSize(new java.awt.Dimension(104, 22));
        addTutorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTutorBtnActionPerformed(evt);
            }
        });

        removeTutorBtn.setText("Remove Tutor");
        removeTutorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTutorBtnActionPerformed(evt);
            }
        });

        findTutorBtn.setText("Find Tutor");
        findTutorBtn.setMaximumSize(new java.awt.Dimension(104, 22));
        findTutorBtn.setMinimumSize(new java.awt.Dimension(104, 22));
        findTutorBtn.setPreferredSize(new java.awt.Dimension(104, 22));
        findTutorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findTutorBtnActionPerformed(evt);
            }
        });

        modifyTutorBtn.setText("Modify Tutor");
        modifyTutorBtn.setMaximumSize(new java.awt.Dimension(104, 22));
        modifyTutorBtn.setMinimumSize(new java.awt.Dimension(104, 22));
        modifyTutorBtn.setPreferredSize(new java.awt.Dimension(104, 22));
        modifyTutorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyTutorBtnActionPerformed(evt);
            }
        });

        viewTutorsBtn.setText("View Tutors");
        viewTutorsBtn.setMaximumSize(new java.awt.Dimension(104, 22));
        viewTutorsBtn.setMinimumSize(new java.awt.Dimension(104, 22));
        viewTutorsBtn.setPreferredSize(new java.awt.Dimension(104, 22));
        viewTutorsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTutorsBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tutor Management");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        reportBtn.setText("Tutor Reports");
        reportBtn.setMaximumSize(new java.awt.Dimension(104, 22));
        reportBtn.setMinimumSize(new java.awt.Dimension(104, 22));
        reportBtn.setPreferredSize(new java.awt.Dimension(104, 22));
        reportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeTutorBtn)
                            .addComponent(findTutorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifyTutorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewTutorsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addTutorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addTutorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(removeTutorBtn)
                .addGap(17, 17, 17)
                .addComponent(findTutorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(modifyTutorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(viewTutorsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(reportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(backBtn)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addTutorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTutorBtnActionPerformed
        JDialog addDialog = new AddDialog(this, true);
        addDialog.setVisible(true);
    }//GEN-LAST:event_addTutorBtnActionPerformed

    private void removeTutorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTutorBtnActionPerformed
        JDialog removeDialog = new RemoveDialog(this, true);
        removeDialog.setVisible(true);
    }//GEN-LAST:event_removeTutorBtnActionPerformed

    private void findTutorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findTutorBtnActionPerformed
        JDialog findDialog = new FindDialog(this, true);
        findDialog.setVisible(true);
    }//GEN-LAST:event_findTutorBtnActionPerformed

    private void modifyTutorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyTutorBtnActionPerformed
        JDialog modifyDialog = new ModifyDialog(this, true);
        modifyDialog.setVisible(true);
    }//GEN-LAST:event_modifyTutorBtnActionPerformed

    private void viewTutorsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTutorsBtnActionPerformed
        JDialog viewDialog = new ViewDialog(this, true);
        viewDialog.setVisible(true);
    }//GEN-LAST:event_viewTutorsBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        MainFrame main = new MainFrame();
        main.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void reportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnActionPerformed
        JDialog viewDialog = new ReportDialog(this, true);
        viewDialog.setVisible(true);
    }//GEN-LAST:event_reportBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TutorManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TutorManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TutorManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TutorManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutorManagementFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTutorBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton findTutorBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton modifyTutorBtn;
    private javax.swing.JButton removeTutorBtn;
    private javax.swing.JButton reportBtn;
    private javax.swing.JButton viewTutorsBtn;
    // End of variables declaration//GEN-END:variables
}
