/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Boundary.TutorialGroup;

import ADT.Impl.ArrayList;
import Entity.Student;
import Entity.TutorialGroup;
import Utility.TutorialGroupUtil;
import java.util.function.BiFunction;
import javax.swing.JDialog;

/**
 *
 * @author CY
 */
public class ReportDialog extends javax.swing.JDialog {

    /**
     * Creates new form ReportDialog
     */
    public ReportDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        this.modal = modal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        topFiveMostStudentBtn = new javax.swing.JButton();
        topFiveLeastStudentBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Generate Tutorial Group Report");

        topFiveMostStudentBtn.setText("Top 5 tutorial group with most students");
        topFiveMostStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topFiveMostStudentBtnActionPerformed(evt);
            }
        });

        topFiveLeastStudentBtn.setText("Top 5 tutorial group with least students");
        topFiveLeastStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topFiveLeastStudentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(topFiveMostStudentBtn)
                            .addComponent(topFiveLeastStudentBtn))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(topFiveMostStudentBtn)
                .addGap(41, 41, 41)
                .addComponent(topFiveLeastStudentBtn)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void topFiveMostStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topFiveMostStudentBtnActionPerformed
        ArrayList<TutorialGroup> tutorialGroupList = TutorialGroupUtil.getTutorialGroupDescendingByStudentNo();
        JDialog tutorialGroupDialog = new ReportResultDialog(parent, modal, (ArrayList<TutorialGroup>) tutorialGroupList.subList(0, 4));
        tutorialGroupDialog.setVisible(true);
    }//GEN-LAST:event_topFiveMostStudentBtnActionPerformed

    private void topFiveLeastStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topFiveLeastStudentBtnActionPerformed
        ArrayList<TutorialGroup> tutorialGroupList = TutorialGroupUtil.getTutorialGroupAscendingByStudentNo();
        JDialog tutorialGroupDialog = new ReportResultDialog(parent, modal, (ArrayList<TutorialGroup>) tutorialGroupList.subList(0, 4));
        tutorialGroupDialog.setVisible(true);
    }//GEN-LAST:event_topFiveLeastStudentBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReportDialog dialog = new ReportDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    java.awt.Frame parent;
    boolean modal;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton topFiveLeastStudentBtn;
    private javax.swing.JButton topFiveMostStudentBtn;
    // End of variables declaration//GEN-END:variables
}
