/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Boundary.TutorialGroup;

import javax.swing.JDialog;


/**
 *
 * @author CY
 */
public class TutorialGroupManagementFrame extends javax.swing.JFrame {

    /**
     * Creates new form Tutor
     */
    public TutorialGroupManagementFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addTutorialGroupBtn = new javax.swing.JButton();
        removeTutorialGroupBtn = new javax.swing.JButton();
        findTutorialGroupBtn = new javax.swing.JButton();
        modifyTutorialGroupBtn = new javax.swing.JButton();
        viewTutorialGroupsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        addTutorialGroupBtn.setText("Add Tutorial Group");
        addTutorialGroupBtn.setMaximumSize(new java.awt.Dimension(104, 22));
        addTutorialGroupBtn.setMinimumSize(new java.awt.Dimension(104, 22));
        addTutorialGroupBtn.setPreferredSize(new java.awt.Dimension(104, 22));
        addTutorialGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTutorialGroupBtnActionPerformed(evt);
            }
        });

        removeTutorialGroupBtn.setText("Remove Tutorial Group");
        removeTutorialGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTutorialGroupBtnActionPerformed(evt);
            }
        });

        findTutorialGroupBtn.setText("Find Tutorial Group");
        findTutorialGroupBtn.setMaximumSize(new java.awt.Dimension(104, 22));
        findTutorialGroupBtn.setMinimumSize(new java.awt.Dimension(104, 22));
        findTutorialGroupBtn.setPreferredSize(new java.awt.Dimension(104, 22));
        findTutorialGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findTutorialGroupBtnActionPerformed(evt);
            }
        });

        modifyTutorialGroupBtn.setText("Modify Tutorial Group");
        modifyTutorialGroupBtn.setMaximumSize(new java.awt.Dimension(104, 22));
        modifyTutorialGroupBtn.setMinimumSize(new java.awt.Dimension(104, 22));
        modifyTutorialGroupBtn.setPreferredSize(new java.awt.Dimension(104, 22));
        modifyTutorialGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyTutorialGroupBtnActionPerformed(evt);
            }
        });

        viewTutorialGroupsBtn.setText("View Tutorial Groups");
        viewTutorialGroupsBtn.setMaximumSize(new java.awt.Dimension(104, 22));
        viewTutorialGroupsBtn.setMinimumSize(new java.awt.Dimension(104, 22));
        viewTutorialGroupsBtn.setPreferredSize(new java.awt.Dimension(104, 22));
        viewTutorialGroupsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTutorialGroupsBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tutorial Group Management");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(removeTutorialGroupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addTutorialGroupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(findTutorialGroupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modifyTutorialGroupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewTutorialGroupsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(addTutorialGroupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(removeTutorialGroupBtn)
                .addGap(17, 17, 17)
                .addComponent(findTutorialGroupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(modifyTutorialGroupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(viewTutorialGroupsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addTutorialGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTutorialGroupBtnActionPerformed
        JDialog addDialog = new AddDialog(this, true);
        addDialog.setVisible(true);
    }//GEN-LAST:event_addTutorialGroupBtnActionPerformed

    private void removeTutorialGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTutorialGroupBtnActionPerformed
        JDialog removeDialog = new RemoveDialog(this, true);
        removeDialog.setVisible(true);
    }//GEN-LAST:event_removeTutorialGroupBtnActionPerformed

    private void findTutorialGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findTutorialGroupBtnActionPerformed
        JDialog findDialog = new FindDialog(this, true);
        findDialog.setVisible(true);
    }//GEN-LAST:event_findTutorialGroupBtnActionPerformed

    private void modifyTutorialGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyTutorialGroupBtnActionPerformed
        JDialog modifyDialog = new ModifyDialog(this, true);
        modifyDialog.setVisible(true);
    }//GEN-LAST:event_modifyTutorialGroupBtnActionPerformed

    private void viewTutorialGroupsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTutorialGroupsBtnActionPerformed
        JDialog viewDialog = new ViewDialog(this, true);
        viewDialog.setVisible(true);
    }//GEN-LAST:event_viewTutorialGroupsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TutorialGroupManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TutorialGroupManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TutorialGroupManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TutorialGroupManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutorialGroupManagementFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTutorialGroupBtn;
    private javax.swing.JButton findTutorialGroupBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton modifyTutorialGroupBtn;
    private javax.swing.JButton removeTutorialGroupBtn;
    private javax.swing.JButton viewTutorialGroupsBtn;
    // End of variables declaration//GEN-END:variables
}
