/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Boundary.Programme;

import ADT.Impl.ArrayList;
import ADT.Impl.ArraySetUniqueList;
import ADT.Impl.LinkedSetUniqueList;
import Controller.ProgrammeController;
import Controller.TutorialGroupController;
import Entity.Programme;
import Entity.TutorialGroup;
import java.awt.Color;

/**
 *
 * @author Wai Loc
 */
public class AddTutorialGroup extends javax.swing.JFrame {

    /**
     * Creates new form AddTutorialGroup
     */
    public AddTutorialGroup() {
        initComponents();
    }

    private void initializeTutorialGroupField() {
        TutorialGroupController tutorialGroupController = TutorialGroupController.getInstance();
        ArrayList<TutorialGroup> tutorialGroupList = tutorialGroupController.getTutorialGroupList();
        
        for(TutorialGroup group : tutorialGroupList) {
            tutorialSelectList.addItem(Integer.toString(group.getGroupNumber()));
        }
    }
    
    private void initializeProgrammeField(){
        LinkedSetUniqueList<Programme> programmeList = ProgrammeController.getProgrammeList();
        
        for (Programme programme : programmeList){
            programmeSelectList.addItem(programme.getProgrammeName());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tutorialSelectList = new javax.swing.JComboBox<>();
        initializeTutorialGroupField();
        programmeSelectList = new javax.swing.JComboBox<>();
        initializeProgrammeField();
        addBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        feedbackMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Tutorial Group");

        jLabel2.setText("Tutorial Group:");
        jLabel2.setMaximumSize(new java.awt.Dimension(80, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(80, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 25));

        jLabel3.setText("Add into:");
        jLabel3.setMaximumSize(new java.awt.Dimension(80, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(80, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 25));

        tutorialSelectList.setMaximumSize(new java.awt.Dimension(230, 25));
        tutorialSelectList.setMinimumSize(new java.awt.Dimension(230, 25));
        tutorialSelectList.setPreferredSize(new java.awt.Dimension(230, 25));
        tutorialSelectList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectListItemStateChanged(evt);
            }
        });

        programmeSelectList.setMaximumSize(new java.awt.Dimension(230, 25));
        programmeSelectList.setMinimumSize(new java.awt.Dimension(230, 25));
        programmeSelectList.setPreferredSize(new java.awt.Dimension(230, 25));
        programmeSelectList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectListItemStateChanged(evt);
            }
        });

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        feedbackMsg.setMaximumSize(new java.awt.Dimension(130, 25));
        feedbackMsg.setMinimumSize(new java.awt.Dimension(130, 25));
        feedbackMsg.setPreferredSize(new java.awt.Dimension(130, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addGap(35, 35, 35)
                        .addComponent(cancelBtn))
                    .addComponent(jLabel1))
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(feedbackMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tutorialSelectList, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(programmeSelectList, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tutorialSelectList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(programmeSelectList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(feedbackMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String selectedProgramme = programmeSelectList.getSelectedItem().toString();
        int tutorialGroupNumber =  Integer.parseInt(tutorialSelectList.getSelectedItem().toString());
        
        try{
            ProgrammeController programmeController = new ProgrammeController();
            Programme programme = programmeController.findProgrammeByName(selectedProgramme);

            TutorialGroupController tgController = TutorialGroupController.getInstance();
            TutorialGroup tutorialGroup = tgController.findTutorialGroupByGroupNumber(tutorialGroupNumber);
            ArraySetUniqueList<TutorialGroup> tutorialGroupList = programme.getTutorialGroupList();
            boolean result = tutorialGroupList.add(tutorialGroup);
            programme.setTutorialGroupList(tutorialGroupList);
            
            if (result){
                feedbackMsg.setForeground(new Color(56,118,29));
                feedbackMsg.setText("Tutorial group added successfully!");
            } else {
                feedbackMsg.setForeground(Color.red);
                feedbackMsg.setText("Duplicated tutorial group!");
            }
        } catch (IndexOutOfBoundsException ex){
            feedbackMsg.setForeground(Color.red);
            feedbackMsg.setText("Failed to add tutorial group!");
        }
        
    }//GEN-LAST:event_addBtnActionPerformed
    
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void selectListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectListItemStateChanged
        feedbackMsg.setText("");
    }//GEN-LAST:event_selectListItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTutorialGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTutorialGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTutorialGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTutorialGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTutorialGroup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel feedbackMsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> programmeSelectList;
    private javax.swing.JComboBox<String> tutorialSelectList;
    // End of variables declaration//GEN-END:variables
}
