/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Boundary.Programme;

/**
 *
 * @author Wai Loc
 */
public class ProgrammeManagementFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ProgrammeManagementFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        addProgrammeBtn = new javax.swing.JButton();
        removeProgrammeBtn = new javax.swing.JButton();
        viewProgrammeBtn = new javax.swing.JButton();
        findProgrammeBtn = new javax.swing.JButton();
        editProgrammeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Programme Management");

        addProgrammeBtn.setText("Add Programme");
        addProgrammeBtn.setMaximumSize(new java.awt.Dimension(134, 30));
        addProgrammeBtn.setMinimumSize(new java.awt.Dimension(134, 30));
        addProgrammeBtn.setPreferredSize(new java.awt.Dimension(134, 30));
        addProgrammeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProgrammeBtnActionPerformed(evt);
            }
        });

        removeProgrammeBtn.setText("Remove Programme");
        removeProgrammeBtn.setMaximumSize(new java.awt.Dimension(134, 30));
        removeProgrammeBtn.setMinimumSize(new java.awt.Dimension(134, 30));
        removeProgrammeBtn.setPreferredSize(new java.awt.Dimension(134, 30));
        removeProgrammeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProgrammeBtnActionPerformed(evt);
            }
        });

        viewProgrammeBtn.setText("View Programme");
        viewProgrammeBtn.setMaximumSize(new java.awt.Dimension(134, 30));
        viewProgrammeBtn.setMinimumSize(new java.awt.Dimension(134, 30));
        viewProgrammeBtn.setPreferredSize(new java.awt.Dimension(134, 30));
        viewProgrammeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProgrammeBtnActionPerformed(evt);
            }
        });

        findProgrammeBtn.setText("Find Programme");
        findProgrammeBtn.setMaximumSize(new java.awt.Dimension(134, 30));
        findProgrammeBtn.setMinimumSize(new java.awt.Dimension(134, 30));
        findProgrammeBtn.setPreferredSize(new java.awt.Dimension(134, 30));
        findProgrammeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findProgrammeBtnActionPerformed(evt);
            }
        });

        editProgrammeBtn.setText("Edit Programme");
        editProgrammeBtn.setMaximumSize(new java.awt.Dimension(134, 30));
        editProgrammeBtn.setMinimumSize(new java.awt.Dimension(134, 30));
        editProgrammeBtn.setPreferredSize(new java.awt.Dimension(134, 30));
        editProgrammeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProgrammeBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.setMaximumSize(new java.awt.Dimension(134, 30));
        backBtn.setMinimumSize(new java.awt.Dimension(134, 30));
        backBtn.setPreferredSize(new java.awt.Dimension(134, 30));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(removeProgrammeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewProgrammeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addProgrammeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(findProgrammeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editProgrammeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(addProgrammeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(viewProgrammeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(findProgrammeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(editProgrammeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(removeProgrammeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProgrammeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProgrammeBtnActionPerformed
        AddProgramme addProgramme = new AddProgramme();
        addProgramme.setVisible(true);
    }//GEN-LAST:event_addProgrammeBtnActionPerformed

    private void removeProgrammeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProgrammeBtnActionPerformed
        RemoveProgramme removeProgramme = new RemoveProgramme();
        removeProgramme.setVisible(true);
    }//GEN-LAST:event_removeProgrammeBtnActionPerformed

    private void viewProgrammeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProgrammeBtnActionPerformed
        ViewProgramme viewProgramme = new ViewProgramme();
        viewProgramme.setVisible(true);
    }//GEN-LAST:event_viewProgrammeBtnActionPerformed

    private void findProgrammeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findProgrammeBtnActionPerformed
        FindProgramme findProgramme = new FindProgramme();
        findProgramme.setVisible(true);
    }//GEN-LAST:event_findProgrammeBtnActionPerformed

    private void editProgrammeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProgrammeBtnActionPerformed
        EditProgramme editProgramme = new EditProgramme();
        editProgramme.setVisible(true);
    }//GEN-LAST:event_editProgrammeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgrammeManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgrammeManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgrammeManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgrammeManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgrammeManagementFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProgrammeBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton editProgrammeBtn;
    private javax.swing.JButton findProgrammeBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton removeProgrammeBtn;
    private javax.swing.JButton viewProgrammeBtn;
    // End of variables declaration//GEN-END:variables
}
