/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Boundary.Programme;

import ADT.Impl.ArrayList;
import ADT.Impl.ArraySetUniqueList;
import ADT.Impl.LinkedSetUniqueList;
import Controller.ProgrammeController;
import Controller.TutorialGroupController;
import Entity.*;
import java.awt.Color;

/**
 *
 * @author Wai Loc
 */
public class RemoveTutorialGroup extends javax.swing.JFrame {

    /**
     * Creates new form RemoveTutorialGroup
     */
    public RemoveTutorialGroup() {
        initComponents();
    }

    private void initializeProgrammeField(){
        LinkedSetUniqueList<Programme> programmeList = ProgrammeController.getProgrammeList();
        programmeSelectList.addItem("--");
        
        for (Programme programme : programmeList){
            programmeSelectList.addItem(programme.getProgrammeName());
        }
    }
    
    private void initializeTutorialGroupField(Programme programme) {
        tutorialSelectList.removeAllItems();
        ArraySetUniqueList<TutorialGroup> tutorialGroupList = programme.getTutorialGroupList();
        ArrayList<TutorialGroup> result = new ArrayList<>();
        result.add(tutorialGroupList.get(0));
        boolean shouldInsertLast = true;
        for (int i = 1; i < tutorialGroupList.size(); i++) {
            TutorialGroup tutGroup1 = tutorialGroupList.get(i);
            shouldInsertLast = true;
            for (int j = 0; j < result.size(); j++) {
                TutorialGroup tutGroup2 = tutorialGroupList.get(j);
                if (tutGroup1.getGroupNumber() < tutGroup2.getGroupNumber()) {
                    result.add(0, tutGroup1);
                    shouldInsertLast = false;
                    break;
                }
            }
            if (shouldInsertLast) {
                result.add(tutGroup1);
            }
        }
        
        if (result.isEmpty()){
            tutorialSelectList.addItem("--");
            return;
        }
        
        for (TutorialGroup group : result) {
            tutorialSelectList.addItem(Integer.toString(group.getGroupNumber()));
        }
    }
    
    public void displayTutorialGroupListSidebar(){
        String selectedProgramme = programmeSelectList.getSelectedItem().toString();
        try{
            if (selectedProgramme.equals("--")){
                TGListTxtArea.setText("");
                return;
            }

            String output = "";
            ProgrammeController programmeController = new ProgrammeController();
            Programme programme = programmeController.findProgrammeByName(selectedProgramme);
            initializeTutorialGroupField(programme);

            ArraySetUniqueList<TutorialGroup> tutorialGroupList = programme.getTutorialGroupList();
            for (TutorialGroup tg : tutorialGroupList){
                output += tg.toString();
            }

            if (output.equals("")){
                TGListTxtArea.setText("No tutorial groups found!");
            } else {
                TGListTxtArea.setText(output);
            }

        } catch (IndexOutOfBoundsException ex){
            TGListTxtArea.setText("No tutorial groups found!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TGListTxtArea = new javax.swing.JTextArea();
        programmeSelectList = new javax.swing.JComboBox<>();
        initializeProgrammeField();
        feedbackMsg = new javax.swing.JLabel();
        removeBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tutorialSelectList = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Remove Tutorial Group in Programme");

        jLabel3.setText("Programme:");
        jLabel3.setMaximumSize(new java.awt.Dimension(80, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(80, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 25));

        TGListTxtArea.setEditable(false);
        TGListTxtArea.setColumns(20);
        TGListTxtArea.setRows(5);
        jScrollPane2.setViewportView(TGListTxtArea);

        programmeSelectList.setMaximumSize(new java.awt.Dimension(230, 25));
        programmeSelectList.setMinimumSize(new java.awt.Dimension(230, 25));
        programmeSelectList.setPreferredSize(new java.awt.Dimension(230, 25));
        programmeSelectList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                programmeSelectListItemStateChanged(evt);
            }
        });

        removeBtn.setText("Remove");
        removeBtn.setMaximumSize(new java.awt.Dimension(80, 25));
        removeBtn.setMinimumSize(new java.awt.Dimension(80, 25));
        removeBtn.setPreferredSize(new java.awt.Dimension(80, 25));
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.setMaximumSize(new java.awt.Dimension(80, 25));
        cancelBtn.setMinimumSize(new java.awt.Dimension(80, 25));
        cancelBtn.setPreferredSize(new java.awt.Dimension(80, 25));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Remove tutorial group:");
        jLabel2.setMaximumSize(new java.awt.Dimension(128, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(128, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(128, 30));

        tutorialSelectList.setMaximumSize(new java.awt.Dimension(110, 30));
        tutorialSelectList.setMinimumSize(new java.awt.Dimension(110, 30));
        tutorialSelectList.setName(""); // NOI18N
        tutorialSelectList.setPreferredSize(new java.awt.Dimension(110, 30));
        tutorialSelectList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialSelectListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(programmeSelectList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(feedbackMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tutorialSelectList, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(programmeSelectList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tutorialSelectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addComponent(feedbackMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void programmeSelectListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_programmeSelectListItemStateChanged
        String selectedProgramme = programmeSelectList.getSelectedItem().toString();
        try{
            if (selectedProgramme.equals("--")){
                TGListTxtArea.setText("");
                return;
            }

            String output = "";
            ProgrammeController programmeController = new ProgrammeController();
            Programme programme = programmeController.findProgrammeByName(selectedProgramme);
            initializeTutorialGroupField(programme);

            ArraySetUniqueList<TutorialGroup> tutorialGroupList = programme.getTutorialGroupList();
            for (TutorialGroup tg : tutorialGroupList){
                output += tg.toString();
            }

            if (output.equals("")){
                TGListTxtArea.setText("No tutorial groups found!");
            } else {
                TGListTxtArea.setText(output);
            }

        } catch (IndexOutOfBoundsException ex){
            TGListTxtArea.setText("No tutorial groups found!");
        }
    }//GEN-LAST:event_programmeSelectListItemStateChanged

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        ProgrammeController progController = new ProgrammeController();
        boolean result = false;
        
        TutorialGroupController tgController = TutorialGroupController.getInstance();
        Programme programme = progController.findProgrammeByName(programmeSelectList.getSelectedItem().toString());
        TutorialGroup tutorialGroup = tgController.findTutorialGroupByGroupNumber(Integer.parseInt(tutorialSelectList.getSelectedItem().toString()));
        result = programme.getTutorialGroupList().remove(tutorialGroup);
        
        if (result){
            displayTutorialGroupListSidebar();
            feedbackMsg.setForeground(new Color(56,118,29));
            feedbackMsg.setText("Tutorial group is successfully removed from programme!");
        } else {
            displayTutorialGroupListSidebar();
            feedbackMsg.setForeground(Color.red);
            feedbackMsg.setText("Failed to remove tutorial group!");
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void tutorialSelectListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialSelectListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tutorialSelectListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveTutorialGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveTutorialGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveTutorialGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveTutorialGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveTutorialGroup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TGListTxtArea;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel feedbackMsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> programmeSelectList;
    private javax.swing.JButton removeBtn;
    private javax.swing.JComboBox<String> tutorialSelectList;
    // End of variables declaration//GEN-END:variables
}
