/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Boundary.Programme;

import ADT.Impl.LinkedSetUniqueList;
import Controller.ProgrammeController;

/**
 *
 * @author Wai Loc
 */
public class ReportsSelection extends javax.swing.JFrame {

    /**
     * Creates new form ReportsSelection
     */
    public ReportsSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        programmeReportsLabel = new javax.swing.JLabel();
        totalFeesReportBtn = new javax.swing.JButton();
        mostGroupsReportBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        programmeReportsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        programmeReportsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        programmeReportsLabel.setText("Programme Reports");

        totalFeesReportBtn.setText("Programmes with highest fees");
        totalFeesReportBtn.setMaximumSize(new java.awt.Dimension(200, 30));
        totalFeesReportBtn.setMinimumSize(new java.awt.Dimension(200, 30));
        totalFeesReportBtn.setPreferredSize(new java.awt.Dimension(200, 30));
        totalFeesReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFeesReportBtnActionPerformed(evt);
            }
        });

        mostGroupsReportBtn.setText("Programmes with most groups");
        mostGroupsReportBtn.setMaximumSize(new java.awt.Dimension(220, 30));
        mostGroupsReportBtn.setMinimumSize(new java.awt.Dimension(220, 30));
        mostGroupsReportBtn.setPreferredSize(new java.awt.Dimension(220, 30));
        mostGroupsReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostGroupsReportBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalFeesReportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(programmeReportsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mostGroupsReportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(125, 125, 125))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelBtn)
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(programmeReportsLabel)
                .addGap(50, 50, 50)
                .addComponent(totalFeesReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(mostGroupsReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(cancelBtn)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalFeesReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFeesReportBtnActionPerformed
        ProgrammeController programmeController = new ProgrammeController();
        ReportsResult reportsResult = new ReportsResult("Top Programmes with Highest Tuition Fees", programmeController.reportProgrammeByFees());
        reportsResult.setVisible(true);
    }//GEN-LAST:event_totalFeesReportBtnActionPerformed

    private void mostGroupsReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostGroupsReportBtnActionPerformed
        ProgrammeController programmeController = new ProgrammeController();
        ReportsResult reportsResult = new ReportsResult("Top Programmes with Highest Number of Tutorial Groups", programmeController.reportProgrammeByTotalGroups());
        reportsResult.setVisible(true);
    }//GEN-LAST:event_mostGroupsReportBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportsSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton mostGroupsReportBtn;
    private javax.swing.JLabel programmeReportsLabel;
    private javax.swing.JButton totalFeesReportBtn;
    // End of variables declaration//GEN-END:variables
}
